spring:
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  sql:
    init:
      mode: always
      data-locations: classpath*:db/h2/data.sql
  jpa:
    hibernate:
      ddl-auto: create  # If deploy server, have to change please
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID} # 구글 API콘솔로 발급받은 ID
            clientSecret: ${G_CLIENT_SECRET} # 구글 API콘솔로 발급받은 SECRET
            scope:
              - email
              - profile
          github:
            clientId: ${H_CLIENT_ID}
            clientSecret: ${H_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # (== http://localhost:8080/login/oauth2/code/google)
            authorization-grant-type: authorization_code
            client-name: GitHub
            scope:
              - user
              - repo
jwt:
  secret-key: ${JWT_SECRET_KEY}  # 환경 변수로 설정했음
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420