spring:
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 684018147936-rs4aqc1ld3f7ui6cff635hoh5bqlno8s.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: asd123123123123123123123123123123123
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 600

